// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'asdf',
    appId: 'asdf',
    messagingSenderId: 'asdf',
    projectId: 'asdf',
    storageBucket: 'asdf',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'asdf',
    appId: 'asfd',
    messagingSenderId: 'asf',
    projectId: 'afss',
    storageBucket: 'asdf',
    iosClientId: 'asdf',
    iosBundleId: 'asdf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'asdf',
    appId: 'asdf',
    messagingSenderId: 'asf',
    projectId: 'asdf',
    storageBucket: 'asdf',
    iosClientId: 'asdf',
    iosBundleId: 'asdf',
  );
}
